# Generated by Django 3.1.2 on 2020-10-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetenzen',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kompetenzen.kompetenzen_group'),
        ),
        migrations.AddField(
            model_name='kompetenzen',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kompetenzen.type'),
        ),
    ]
