# Generated by Django 3.1.2 on 2020-10-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0002_auto_20201024_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kompetenzen',
            new_name='course',
        ),
        migrations.RenameModel(
            old_name='kompetenzen_group',
            new_name='course_group',
        ),
        migrations.RenameModel(
            old_name='type',
            new_name='course_type',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='signedup',
            new_name='signed_up',
        ),
    ]
