# Generated by Django 3.1.2 on 2020-10-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0003_auto_20201025_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_group',
            name='maxcredits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course_group',
            name='mincredits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='signed_up',
            field=models.CharField(choices=[('HS19', 'HS19'), ('FS20', 'FS20'), ('HS20', 'HS20'), ('FS21', 'FS21'), ('HS21', 'HS21'), ('FS22', 'FS22'), ('HS22', 'HS22'), ('FS23', 'FS23')], max_length=10, null=True),
        ),
    ]
