# Generated by Django 3.1.2 on 2020-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0005_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='signed_up',
            field=models.CharField(choices=[('n/a', 'n/a'), ('HS19', 'HS19'), ('FS20', 'FS20'), ('HS20', 'HS20'), ('FS21', 'FS21'), ('HS21', 'HS21'), ('FS22', 'FS22'), ('HS22', 'HS22'), ('FS23', 'FS23')], max_length=10, null=True),
        ),
    ]
