# Generated by Django 3.1.2 on 2020-11-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0007_auto_20201101_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kompetenzen.course_semester'),
        ),
    ]
