# Generated by Django 3.1.2 on 2020-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0008_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
